"""add users table & update todos relationship

Revision ID: a3a449268b49
Revises: 5a970ae291f4
Create Date: 2024-01-06 11:17:37.265617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3a449268b49'
down_revision: Union[str, None] = '5a970ae291f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_table_email'), 'users_table', ['email'], unique=True)
    op.create_index(op.f('ix_users_table_hashed_password'), 'users_table', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_users_table_id'), 'users_table', ['id'], unique=False)
    op.create_index(op.f('ix_users_table_updated_at'), 'users_table', ['updated_at'], unique=False)
    op.create_table('todos_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_table_id'), 'todos_table', ['id'], unique=False)
    op.create_index(op.f('ix_todos_table_title'), 'todos_table', ['title'], unique=False)
    op.create_index(op.f('ix_todos_table_updated_at'), 'todos_table', ['updated_at'], unique=False)
    op.drop_index('ix_todos_created_at', table_name='todos')
    op.drop_index('ix_todos_description', table_name='todos')
    op.drop_index('ix_todos_id', table_name='todos')
    op.drop_index('ix_todos_title', table_name='todos')
    op.drop_index('ix_todos_updated_at', table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='todos_pkey')
    )
    op.create_index('ix_todos_updated_at', 'todos', ['updated_at'], unique=False)
    op.create_index('ix_todos_title', 'todos', ['title'], unique=False)
    op.create_index('ix_todos_id', 'todos', ['id'], unique=False)
    op.create_index('ix_todos_description', 'todos', ['description'], unique=False)
    op.create_index('ix_todos_created_at', 'todos', ['created_at'], unique=False)
    op.drop_index(op.f('ix_todos_table_updated_at'), table_name='todos_table')
    op.drop_index(op.f('ix_todos_table_title'), table_name='todos_table')
    op.drop_index(op.f('ix_todos_table_id'), table_name='todos_table')
    op.drop_table('todos_table')
    op.drop_index(op.f('ix_users_table_updated_at'), table_name='users_table')
    op.drop_index(op.f('ix_users_table_id'), table_name='users_table')
    op.drop_index(op.f('ix_users_table_hashed_password'), table_name='users_table')
    op.drop_index(op.f('ix_users_table_email'), table_name='users_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
