"""update datetime format

Revision ID: 4ea029956835
Revises: d627296cc28b
Create Date: 2024-01-06 15:42:19.410043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea029956835'
down_revision: Union[str, None] = 'd627296cc28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todos_table_updated_at', table_name='todos_table')
    op.drop_index('ix_users_table_updated_at', table_name='users_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_table_updated_at', 'users_table', ['updated_at'], unique=False)
    op.create_index('ix_todos_table_updated_at', 'todos_table', ['updated_at'], unique=False)
    # ### end Alembic commands ###
