"""add users table username field

Revision ID: d627296cc28b
Revises: a3a449268b49
Create Date: 2024-01-06 12:14:28.759599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd627296cc28b'
down_revision: Union[str, None] = 'a3a449268b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('username', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_table_username'), 'users_table', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_table_username'), table_name='users_table')
    op.drop_column('users_table', 'username')
    # ### end Alembic commands ###
