"""change disables to email_verified in user __table__

Revision ID: 5c2038a0ef7d
Revises: 4ea029956835
Create Date: 2024-01-06 21:46:22.938127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2038a0ef7d'
down_revision: Union[str, None] = '4ea029956835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.drop_column('users_table', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users_table', 'email_verified')
    # ### end Alembic commands ###
