"""Add Tables

Revision ID: e08cffab0eb4
Revises: 
Create Date: 2024-01-10 14:22:34.852505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08cffab0eb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_table_email'), 'users_table', ['email'], unique=True)
    op.create_index(op.f('ix_users_table_hashed_password'), 'users_table', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_users_table_id'), 'users_table', ['id'], unique=False)
    op.create_index(op.f('ix_users_table_username'), 'users_table', ['username'], unique=True)
    op.create_table('todos_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_table_id'), 'todos_table', ['id'], unique=False)
    op.create_index(op.f('ix_todos_table_title'), 'todos_table', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_table_title'), table_name='todos_table')
    op.drop_index(op.f('ix_todos_table_id'), table_name='todos_table')
    op.drop_table('todos_table')
    op.drop_index(op.f('ix_users_table_username'), table_name='users_table')
    op.drop_index(op.f('ix_users_table_id'), table_name='users_table')
    op.drop_index(op.f('ix_users_table_hashed_password'), table_name='users_table')
    op.drop_index(op.f('ix_users_table_email'), table_name='users_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
